---

# Clean the flash on all stack members

    - name: Clean up flash on all stack members          
      shell: |
        spawn ssh {{ansible_user}}@{{inventory_hostname}}
        expect "*?assword:*"
        send "{{ansible_password}}\r"
        expect "#"
        send "install remove inactive\r"
        set timeout 300
        expect "Do you want to remove the above files?"
        send "y\r"
        set timeout 60
        expect "#"
        exit 0
        
      args:
        executable: /usr/bin/expect
      delegate_to: localhost    
      
